apiVersion: v2
name: vab
description: Venafi Afterburners Parent Chart
type: application
version: 0.0.24
appVersion: 0.0.24
dependencies:
- name: linkerd2
  version: "~2.8.1"
  repository: "@linkerd"
- name: ingress-nginx
  version: "~2.11.0"
  repository: "@ingress-nginx"
- name: cert-manager
  version: "v0.15.2"
  repository: "@jetstack"
- name: ledger
  tags:
  - local
  version: 0.0.24
- name: txnsim
  tags:
  - local
  version: 0.0.24
