namespaces:
    - name: core
      linkerdEnabled: true

ledger:
  namespace: core

txnsim:
  namespace: core
  ledgerServiceAddress: http://ledger-svc

vault:
  server:
    dataStorage:
      enabled: false
    auditStorage:
      enabled: false
    dev:
      enabled: true
    ui:
      enabled: true

global:
  domainName: gloomy-williams.wapbot.co.uk
