apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        name: {{ .Values.serviceName }}
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: cockroachdb-secret
          mountPath: /cockroachdb-certs
          readOnly: true
        env:
        - name: OCVAB_LEDGER_DB
          value: "user={{ .Values.serviceName }} host=cockroachdb-public.cockroachdb.svc.cluster.local port=26257 dbname=transactions sslmode=verify-full sslcert=/cockroachdb-certs/tls.crt sslkey=/cockroachdb-certs/tls.key sslrootcert=/cockroachdb-certs/ca.crt"
      volumes:
      - name: cockroachdb-secret
        secret:
          secretName: cockroachdb-{{ .Values.serviceName }}

