apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ledger
  name: ledger
  namespace: {{ default "core" .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      containers:
      - image: yoink00/ledger:{{ default "latest" .Values.image.tag }}
        name: ledger
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

