apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}-ingress
  namespace: {{ default "core" .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
  - host: {{ .Values.global.domainName }}
    http:
      paths:
      - path: /{{ default "core" .Values.namespace }}/{{ .Values.serviceName }}(/|$)(.*)
        backend:
          serviceName: {{ .Values.serviceName }}-svc
          servicePort: 80
