apiVersion: v1
kind: Service
metadata:
  name: ledger
  namespace: {{ default "core" .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ledger