apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Value.serviceName }}
webhooks:
- name: '{{ .Value.serviceName }}-svc'
  clientConfig:
    service:
      name: '{{ .Value.serviceName }}-svc'
      namespace: core
      path: "/"
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV0ekNDQTUrZ0F3SUJBZ0lVUFhJV3BackM0
      aHVacXNJQ1NIaU5uZUQvVlNnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pqRUxNQWtHQTFVRUJoTUNW
      Vk14RlRBVEJnTlZCQW9UREZabGJtRm1hU3dnU1c1akxqRVJNQThHQTFVRQpDeE1JUW5WcGJIUXRh
      VzR4TFRBckJnTlZCQU1USkVSbFpHbGpZWFJsWkNBdElGWmxibUZtYVNCRGJHOTFaQ0JDCmRXbHNk
      QzFKYmlCRFFUQWVGdzB4T1RBM01qVXdNakEwTVRsYUZ3MHlOREEzTWpNd01qQTBORGxhTUhneEN6
      QUoKQmdOVkJBWVRBbFZUTVJVd0V3WURWUVFLRXd4V1pXNWhabWtzSUVsdVl5NHhFVEFQQmdOVkJB
      c1RDRUoxYVd4MApMV2x1TVQ4d1BRWURWUVFERXpaRVpXUnBZMkYwWldRZ0xTQldaVzVoWm1rZ1Ey
      eHZkV1FnUW5WcGJIUXRTVzRnClNXNTBaWEp0WldScFlYUmxJRU5CSUMwZ1J6RXdnZ0VpTUEwR0NT
      cUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQzBoNmNVL3JkVldPVmRzcHg1QTJLZEJn
      SmlaN2NDVVNVanJQL21BQkRtak5RQXA5ZDFvZlpRaXN4WQpTWmhmZGh4YTNlU3lRK1dvaS8xMXR6
      MUJWRlpaSDVjMGZQWnpWdnBOVWZUMkxHQVlybDRSTlFkYUpWZERGbkRHCk5Hb1hJNEQvMEtES0xF
      Smxqdk9jdXhCYkJJKzJicDFWRGRTUUdzb0dPc2krdDcyaWh1MjRzcGl3UEJ6d3p2SDYKQVpvRzFi
      SjAzaUZ4MFJLdmxLWTJra1p5MURuMGUvRkVFWHZwZEUxQ1Z4ZTJoZURHY2dZZHBZTkNyZ1B5Ti9v
      MwpHSTlKblIwZXJYQmZPenRMamhjNTlaUHRRcVZYbjNibCtKMERNQXhva1FnVnVteWU3VjlvRSt3
      QWJtbEZxeEt0CndRYlVMcVk3dTl1N1lFa09mT2tJUjhGUlJTSS9BZ01CQUFHamdnRkpNSUlCUlRB
      T0JnTlZIUThCQWY4RUJBTUMKQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdR
      VWFtVGIrNC9RZjFtbjhuYjl6V3lyTS9RSApjV0l3SHdZRFZSMGpCQmd3Rm9BVTZTY0dDTEZlQ2s1
      eXArazdsRWpURnRGc3BCb3dkUVlJS3dZQkJRVUhBUUVFCmFUQm5NR1VHQ0NzR0FRVUZCekFDaGxs
      b2RIUndPaTh2WW5WcGJIUnBibU5oTG5abGJtRm1hUzVqYkc5MVpDOTIKTVM5aWRXbHNkR2x1WTJF
      dlkyRXZOV1ZrWldGak56QXROR05oWmkweE1XVTVMVGc1WVRVdFpXSmpZV1ZqWVRnMQpaall3TFZK
      dmIzUkRRVEJyQmdOVkhSOEVaREJpTUdDZ1hxQmNobHBvZEhSd09pOHZZblZwYkhScGJtTmhMblps
      CmJtRm1hUzVqYkc5MVpDOTJNUzlpZFdsc2RHbHVZMkV2WTNKc0x6VmxaR1ZoWXpjd0xUUmpZV1l0
      TVRGbE9TMDQKT1dFMUxXVmlZMkZsWTJFNE5XWTJNQzFTYjI5MFEwRXdEUVlKS29aSWh2Y05BUUVM
      QlFBRGdnRUJBQ2swVDg2bQp0UjNyL002ZGtDNFkxL3BaZmI0NEJ2TGhUOEZIS25taitxcStCQUxO
      Mm1CSGIwMFc4UkFwOHd2SzJ6dVdzODByCkEySHQybkg3TWNWVXQ0RVZLQjNaU0xDMDFlTGZ3Vk9R
      djRZWXpPbFpyTEMzL1FsZlZOTDNXTzBwdHlnQk1TNWwKTHI2a0dvZ0pqYmpVQ2NXNGo4SE11YUd2
      WEhpTGx5SU96V1U0d2pHUFM1WWpmL1JHdzBWRkpVdjhZM0d1NitPRApjcFA3U2UyU3F0K2thR2Y5
      NVFpaHA1b01QeEFCRXNVQzdkeHc4aVJCWDZlaEF5SkFwQjBDT3k4a1orelVrM1VmCm1VdTI1ell4
      NzhlcWN1VkpLZG5oZnl2OTFPU3Nya1RSaEpUenRYa2JqQlBhR1d1WW5QaERSVkJPdy83RkZxZzMK
      WmpLcHBkcnVnRERMd3cwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlEdlRDQ0FxV2dBd0lCQWdJVWNGM1UyM3FHNlNxWmRqcm1UKzdjaXMx
      a0dVTXdEUVlKS29aSWh2Y05BUUVMCkJRQXdaakVMTUFrR0ExVUVCaE1DVlZNeEZUQVRCZ05WQkFv
      VERGWmxibUZtYVN3Z1NXNWpMakVSTUE4R0ExVUUKQ3hNSVFuVnBiSFF0YVc0eExUQXJCZ05WQkFN
      VEpFUmxaR2xqWVhSbFpDQXRJRlpsYm1GbWFTQkRiRzkxWkNCQwpkV2xzZEMxSmJpQkRRVEFlRncw
      eE9UQTNNalV3TWpBME1UbGFGdzB5T1RBM01qSXdNakEwTkRsYU1HWXhDekFKCkJnTlZCQVlUQWxW
      VE1SVXdFd1lEVlFRS0V3eFdaVzVoWm1rc0lFbHVZeTR4RVRBUEJnTlZCQXNUQ0VKMWFXeDAKTFds
      dU1TMHdLd1lEVlFRREV5UkVaV1JwWTJGMFpXUWdMU0JXWlc1aFpta2dRMnh2ZFdRZ1FuVnBiSFF0
      U1c0ZwpRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFJyblhZ
      UkJTMzk4eEJyc0tFClJrOUhtait5V04rYlI0ZXN1NmZiNlcvd2lwM2xsWDE4Rk10L1M1by9VYUx3
      QlhvcjFHNm1GdStqZGxkQ0xGK2EKMHFobnF2NmNOV1Jjb2JSd3psVGFSZyt0M095UDFnUEwrZEhI
      SWNJSnZLTkg3ZWZuVnVCSFNrbXF1bStWbGdnKwowWnU3TnBOa1RwZFBJS0xDNEdmNmN5VC95dUZt
      VzF3bEc0VkZ3bVlyRGF0OUZFYkJSOFpRKzhJMnVEblNMdGdxCnZZK0I2N1duSTg1WnE2SFFjYjZl
      dFJ2NFc1T1l4YU9nYTN2bEtMZUIyQVlCZnZVK1BHbURMb2tVWU1wVkUvTUMKSlZOVVY1bkIvK1NQ
      THRyMnF3U0NiN29rZWhXOUJNd0RMT3hhWUI0b1R1TjJHeUllRGp0YlY2TGlYOFpSN2Mvbgp3TDdS
      QWdNQkFBR2pZekJoTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9N
      QjBHCkExVWREZ1FXQkJUcEp3WUlzVjRLVG5LbjZUdVVTTk1XMFd5a0dqQWZCZ05WSFNNRUdEQVdn
      QlRwSndZSXNWNEsKVG5LbjZUdVVTTk1XMFd5a0dqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFz
      cHMrZHMrNTQyWENndlg3RUdUWQpEWWZ2dkd4UW1FdFdpYkc0QXZLTlZuTy9obzg3T1Bkb0xkeGlp
      L2dXTmRFMWNIR1NublJHdjhUQ0xFUnA1MmVLCmlQZUgzdDd5amxTU2drZCs0bllTQ04waTMwVFM0
      eXNGdzJSTXlnb1k0bi92TkhPZkptb09QM1VIQ0JHUnhJYlkKNWFOOGxrelRUUDVwUVVPcUpyNGtD
      Rmx6NlVhM0F3SkZocm5iUFVzWFNvS3crczhCeUhqNVozUmhGOFcwVWhsSApTekFBVVlDdzMyV0hl
      ODdvMENEa3JCVWhkNndLMDdzQjl1NGZBYUR6RUdkRFVTamNCR3V6WlUyNEdCS0xFMURjCkpIWWpS
      QmtNQ0lKYVIzOUhlL2p0anJhTHA2dzRlYStTVng0NVNvVFZtY2E5ZU51bSt0WUs3Tkp5czUwWStD
      bmsKUlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["secrets"]