apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
webhooks:
- name: '{{ .Values.serviceName }}-svc.{{ .Release.Namespace }}.svc.cluster.local'
  failurePolicy: Ignore
  clientConfig:
    service:
      name: '{{ .Values.serviceName }}-svc'
      namespace: core
      path: "/"
    caBundle: |
      {{ .Values.caBundle | nindent 6 }}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["secrets"]
  namespaceSelector:
    matchLabels:
      secret-fixer: enabled
