apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: {{ .Values.serviceName }}
