name: 'Build'

on:
  push:
    paths: 
    - 'go/**'
    - 'docker/**'
    branches:
    - master
  pull_request:
    paths: 
    - 'go/**'
    - 'docker/**'

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Ledger Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: yoink00/ledger
        dockerfile: docker/ledger/Dockerfile
        path: go
        build_args: GIT_COMMIT_ID=${{ github.sha }}
        tag_with_ref: true
        tag_with_sha: false
        push: ${{ startsWith(github.ref, 'refs/tags') && github.event_name == 'push' }}

    - name: Build Txnsim Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: yoink00/txnsim
        dockerfile: docker/txnsim/Dockerfile
        path: go
        build_args: GIT_COMMIT_ID=${{ github.sha }}
        tag_with_ref: true
        tag_with_sha: false
        push: ${{ startsWith(github.ref, 'refs/tags') && github.event_name == 'push' }}

