name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./google.json
    defaults:
      run:
        working-directory: terraform/envs/dev
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Get Google Secret
      run: 'echo "$GCP_SERVICE_ACCOUNT" > google.json'
      shell: bash
      env:
        GCP_SERVICE_ACCOUNT: ${{secrets.GCP_SERVICE_ACCOUNT}}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve

