name: 'Terraform'

on:
  push:
    paths: 
    - 'terraform/**'
    branches:
    - master
  pull_request:
    paths: 
    - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{github.workspace}}/google.json
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Get Google Secret
      run: 'echo "$GCP_SERVICE_ACCOUNT" > google.json'
      shell: bash
      env:
        GCP_SERVICE_ACCOUNT: ${{secrets.GCP_SERVICE_ACCOUNT}}

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/envs/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform/envs/dev

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
      working-directory: terraform/envs/dev

